### ISSUE TITLE
关于如何使用的问题

### ISSUE THREAD

**Issue by tianma8023** [chenxuefei-pp/hexo-tag-ossimg#1]
@chenxuefei-pp 你好~
1. 使用标签 `{% ossimg example.png title %}` 之后，通过 `hexo generate` 并未在生成的 HTML 页面中生成相应的 `<img>` 标签，是什么情况呢？
2. 再就是在这个插件的说明中提到了可以自动上传图片资源到阿里云OSS，那么需要上传的图片资源应该放在哪个目录下呢？目录结构又是如何呢？
3. 最后，是不是使用方式有问题呢？烦请赐教~

**Comment by stan-chen** [comment]
@tianma8023 
1. 打开 `post_asset_folder` 选项，这样`new post`的时候就会有一个同名文件夹放图片资源。
2. 在文章中用相对路径，但是不要加名字前缀，比如，图片在同名资源文件夹中 `1.png`，那么引用的时候就直接引用 `{% ossimg 1.png sssss %}`。因为代码中是如下调用hexo API 去查找assets的：
`var asset = PostAsset.findOne({post: this._id, slug: slug});`
所以如果没找到asset就直接返回不处理了。

这代码好久没维护了，应该还是有不少bug。。。不过代码量不多，逻辑也简单，随意改。
推荐用这个 `https://github.com/chenxuefei-pp/hexo-asset-oss` 这部分可以上传所有asset，包括js css，比这个好点。

**Comment by tianma8023** [comment]
@chenxuefei-pp ok，十分感谢！
